### ISSUE TITLE
[Feature Request] Create a roadmap.

### ISSUE THREAD

**Issue by muhsinkutay** [iamnijat/habitonic#7]
I started learning Dart programming language and Flutter framework, if this repository had a roadmap I would try my best at implementing the features.

**Comment by iamnijat** [comment]
@muhsinkutay Almost everything is based on Clean Architecture in production, but I didn't write its tests and in this case, if you want to implement a new feature, you can create and mock the tests, it will be comfortable because I used only bloc for state management, it is test-friendly, you can test other features too by the way.

**Comment by muhsinkutay** [comment]
Thank you very much @iamnijat, I will try creating the tests but for that first I need to learn Clean Architecture and Bloc State Management, I've just heard them for the first time.

**Comment by iamnijat** [comment]
Alright, good luck on that quest

**Comment by muhsinkutay** [comment]
Thank you!
